# Generated by Django 5.0.1 on 2024-05-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dropoff_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='dropoff latitude'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropoff_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='dropoff longitude'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='pickup latitude'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='pickup longitude'),
        ),
    ]
